on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@HEAD
        with:
          sparse-checkout: third_party/blink/renderer
      # https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Howto/Write_an_api_reference/Information_contained_in_a_WebIDL_file#where_to_find_webidl_files
      - run: find -name '*.idl' -printf '// %P\n' -exec cat -- {} \; > chromium.webidl
      - uses: actions/upload-artifact@HEAD
        with:
          path: "*.webidl"
          archive: false          
